name: happy_online_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_rating_bar: ^4.0.1
  animated_bottom_navigation_bar: ^1.2.0
  line_icons: ^2.0.1
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.jpg
  android: true
  ios: true

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
