name: happy_online_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_rating_bar: ^4.0.1
  animated_bottom_navigation_bar: ^1.2.0
  line_icons: ^2.0.1
  firebase_core: ^2.7.1
  cloud_firestore: ^4.4.4
  shared_preferences: ^2.0.20
  firebase_auth: ^4.3.0
  firebase_messaging: ^14.3.0
  uuid: ^3.0.7
  awesome_notifications: ^0.7.4+1
  flutter_webrtc: ^0.9.24
  flutter_rounded_date_picker: ^3.0.2
  flutter_datetime_picker: ^1.5.1
  rxdart: ^0.27.7
  stream_chat_flutter: ^5.3.0
  flutter_launcher_icons: ^0.13.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.jpg
  android: true
  ios: true

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
